### ISSUE TITLE
File type missing in main-script

### ISSUE THREAD

**Issue by hubernikus** [domire8/ros-pycharm-example#3]
It seems to me, that the file typeis  missing in main-script

**Comment by domire8** [comment]
Good observation, this isn't wrong though. By adding `#!/usr/bin/env python3` in the first line, this is still considered a python script. It's actually just for aesthetic reasons, `rosrun turtle_example circler` looks a bit more like a cpp program than `rosrun turtle_example circler.py`.

I like [this](http://www.artificialhumancompanions.com/structure-python-based-ros-package/) guide for python based ROS packages

**Comment by buschbapti** [comment]
It is not wrong indeed and actually the way it should be done for python nodes in ros. As the script you run in python is the equivalent of the executable in c++ you want them to behave similarly. Thus you want to do:

```console
rosrun my_package my_script
```

You don't want to do:

```console
rosrun my_package my_script.py
```

Adding the python shebang `#!/usr/bin/env python ` as first line as your script ensures that you IDE or text editor still resolves that as python.

**Comment by hubernikus** [comment]
Okok. I see. Thanks for the clarifiaction.
